#! /bin/bash


#while read c1
#do

while read c2
do


while read c3
do

#c1
#c2
#c3

echo "../v2/red_iris_n_clases 0.1 ../inputs_iris/$c2.txt $c3 4 salida_plantas_$c2\_$c3.txt ../inputs_iris/conjunto_a_clasificar.txt clasificado_plantas_0.1_$c2\_$c3.out"

../v2/red_iris_n_clases 0.1 ../inputs_iris/$c2.txt $c3 4 salida_plantas_$c2\_$c3.txt ../inputs_iris/conjunto_a_clasificar.txt clasificado_plantas_0.1_$c2\_$c3.out



done < $2 #plantas_neuronas.txt

done < $1 #plantas_name.txt

#done < $1
