#! /bin/bash

echo "Paso 1"
paste $1 $2 > union.txt
echo "Paso 2"
head -3852 union.txt > B.txt
echo "Paso 3"
tail -6148 union.txt > A.txt
echo "Paso 4"
grep -v -e -1 A.txt > Agood.txt
wc -l Agood.txt
grep -e -1 A.txt > Abad.txt
wc -l Abad.txt
grep -e -1 B.txt > Bgood.txt
wc -l Bgood.txt
grep -v -e -1 B.txt > Bbad.txt
wc -l Bbad.txt
gnuplot graphics_creator.gnuplot

rm union.txt A.txt B.txt Agood.txt Abad.txt Bbad.txt Bgood.txt
