#! /bin/bash

ls divisor_de_iris/salida* > tmp_salidas.txt

while read line
do

cp $line a.txt
gnuplot salidas_plantas.gnuplot
mv p.png $line.png 


done < tmp_salidas.txt

rm -rf tmp_salidas.txt a.txt
