#! /bin/bash

./create_data empresas/$1.csv
python transform_data_completing.py 1 32 empresas/$1.csv train_$1.txt
python transform_data_completing.py 0 32 empresas/$1.csv casos_$1.txt

num=7
while read c3
do

echo "./codigo/red_iris 0.001 ./datos_completos/t$c3.txt 10 $num errores.txt ./datos_completos/c$c3.txt ./datos_completos/r$c3.txt"

head -5000 ./datos_completos/train_$1.txt$c3 > datos_completos/t$c3.txt
tail -750 ./datos_completos/casos_$1.txt$c3 > datos_completos/c$c3.txt
./codigo/red_iris 0.001 ./datos_completos/t$c3.txt 10 $num errores.txt ./datos_completos/c$c3.txt ./datos_completos/r$c3.txt
num=$[num+4]

done < numeros.txt

mv datos_completos/ $1/
